apiVersion: v1
kind: Service
metadata:
  labels:
    app: gluuconsul
    env: dev
  name: gluuconsul
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: gluuconsul
    env: dev
  type: ClusterIP
