apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gluuconsul
    env: dev
  name: gluuconsul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluuconsul
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gluuconsul
        env: dev
    spec:
      volumes:
      - name: consul-pv-storage
        persistentVolumeClaim:
         claimName: consul-pv-claim
      containers:
      - args:
        - -server
        - -bootstrap
        image: progrium/consul
        imagePullPolicy: Always
        name: gluuconsul
        ports:
        - containerPort: 8500
          protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: consul-pv-storage
