apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-gluu-server
    env: dev
  name: k8s-gluu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-gluu-server
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-gluu-server
        env: dev
    spec:
      containers:
      - env:
        - name: GLUU_KV_HOST
          value: gluuconsul
        - name: GLUU_KV_PORT
          value: "8500"
        - name: GLUU_OXAUTH_BACKEND
          value: gluuoxauth:8080
        - name: GLUU_OXTRUST_BACKEND
          value: gluuoxtrust:8080
        image: gluufederation/nginx:3.1.1_dev
        imagePullPolicy: IfNotPresent
        name: k8s-gluu-server
        ports:
        - containerPort: 443
          protocol: TCP
